/* tslint:disable */
/* eslint-disable */
/**
 * IndividualStartup API documentation
 * fileContent
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayInfo
 */
export interface DayInfo {
    /**
     * 
     * @type {Date}
     * @memberof DayInfo
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof DayInfo
     */
    price: number;
    /**
     * 
     * @type {boolean}
     * @memberof DayInfo
     */
    occupied: boolean;
}

/**
 * Check if a given object implements the DayInfo interface.
 */
export function instanceOfDayInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "occupied" in value;

    return isInstance;
}

export function DayInfoFromJSON(json: any): DayInfo {
    return DayInfoFromJSONTyped(json, false);
}

export function DayInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'price': json['price'],
        'occupied': json['occupied'],
    };
}

export function DayInfoToJSON(value?: DayInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString().substr(0,10)),
        'price': value.price,
        'occupied': value.occupied,
    };
}

