/* tslint:disable */
/* eslint-disable */
/**
 * IndividualStartup API documentation
 * fileContent
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PensionRoomListPriceOutDTO
 */
export interface PensionRoomListPriceOutDTO {
    /**
     * 
     * @type {number}
     * @memberof PensionRoomListPriceOutDTO
     */
    guestCount: number;
    /**
     * 
     * @type {number}
     * @memberof PensionRoomListPriceOutDTO
     */
    price: number;
}

/**
 * Check if a given object implements the PensionRoomListPriceOutDTO interface.
 */
export function instanceOfPensionRoomListPriceOutDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "guestCount" in value;
    isInstance = isInstance && "price" in value;

    return isInstance;
}

export function PensionRoomListPriceOutDTOFromJSON(json: any): PensionRoomListPriceOutDTO {
    return PensionRoomListPriceOutDTOFromJSONTyped(json, false);
}

export function PensionRoomListPriceOutDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PensionRoomListPriceOutDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guestCount': json['guestCount'],
        'price': json['price'],
    };
}

export function PensionRoomListPriceOutDTOToJSON(value?: PensionRoomListPriceOutDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guestCount': value.guestCount,
        'price': value.price,
    };
}

