/* tslint:disable */
/* eslint-disable */
/**
 * IndividualStartup API documentation
 * fileContent
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceElementOutDTO
 */
export interface PriceElementOutDTO {
    /**
     * 
     * @type {string}
     * @memberof PriceElementOutDTO
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PriceElementOutDTO
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof PriceElementOutDTO
     */
    price: number;
}

/**
 * Check if a given object implements the PriceElementOutDTO interface.
 */
export function instanceOfPriceElementOutDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "price" in value;

    return isInstance;
}

export function PriceElementOutDTOFromJSON(json: any): PriceElementOutDTO {
    return PriceElementOutDTOFromJSONTyped(json, false);
}

export function PriceElementOutDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceElementOutDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': json['amount'],
        'price': json['price'],
    };
}

export function PriceElementOutDTOToJSON(value?: PriceElementOutDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'amount': value.amount,
        'price': value.price,
    };
}

