/* tslint:disable */
/* eslint-disable */
/**
 * IndividualStartup API documentation
 * fileContent
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContractInInDTO } from './ContractInInDTO';
import {
    ContractInInDTOFromJSON,
    ContractInInDTOFromJSONTyped,
    ContractInInDTOToJSON,
} from './ContractInInDTO';

/**
 * 
 * @export
 * @interface ReservationInDTO
 */
export interface ReservationInDTO {
    /**
     * 
     * @type {string}
     * @memberof ReservationInDTO
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationInDTO
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationInDTO
     */
    totalPrice?: number;
    /**
     * 
     * @type {ContractInInDTO}
     * @memberof ReservationInDTO
     */
    contract: ContractInInDTO;
    /**
     * 
     * @type {boolean}
     * @memberof ReservationInDTO
     */
    guestWillFillElectronicCheckIn: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReservationInDTO
     */
    plannedArrival: string;
}

/**
 * Check if a given object implements the ReservationInDTO interface.
 */
export function instanceOfReservationInDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "contract" in value;
    isInstance = isInstance && "guestWillFillElectronicCheckIn" in value;
    isInstance = isInstance && "plannedArrival" in value;

    return isInstance;
}

export function ReservationInDTOFromJSON(json: any): ReservationInDTO {
    return ReservationInDTOFromJSONTyped(json, false);
}

export function ReservationInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationInDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'totalPrice': !exists(json, 'totalPrice') ? undefined : json['totalPrice'],
        'contract': ContractInInDTOFromJSON(json['contract']),
        'guestWillFillElectronicCheckIn': json['guestWillFillElectronicCheckIn'],
        'plannedArrival': json['plannedArrival'],
    };
}

export function ReservationInDTOToJSON(value?: ReservationInDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'email': value.email,
        'phone': value.phone,
        'totalPrice': value.totalPrice,
        'contract': ContractInInDTOToJSON(value.contract),
        'guestWillFillElectronicCheckIn': value.guestWillFillElectronicCheckIn,
        'plannedArrival': value.plannedArrival,
    };
}

