/* tslint:disable */
/* eslint-disable */
/**
 * IndividualStartup API documentation
 * fileContent
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceReservationInDTO
 */
export interface ResourceReservationInDTO {
    /**
     * 
     * @type {string}
     * @memberof ResourceReservationInDTO
     */
    resourceUUID: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceReservationInDTO
     */
    guestsCount: number;
}

/**
 * Check if a given object implements the ResourceReservationInDTO interface.
 */
export function instanceOfResourceReservationInDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resourceUUID" in value;
    isInstance = isInstance && "guestsCount" in value;

    return isInstance;
}

export function ResourceReservationInDTOFromJSON(json: any): ResourceReservationInDTO {
    return ResourceReservationInDTOFromJSONTyped(json, false);
}

export function ResourceReservationInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceReservationInDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceUUID': json['resourceUUID'],
        'guestsCount': json['guestsCount'],
    };
}

export function ResourceReservationInDTOToJSON(value?: ResourceReservationInDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resourceUUID': value.resourceUUID,
        'guestsCount': value.guestsCount,
    };
}

